[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path ="src/main.rs"
name ="zero2prod"

[dependencies]
config = "0.14"
actix-web = "4"
tokio = {version = "1",features = ["macros","rt-multi-thread"]}
reqwest = "0.12"
serde = {version = "1",features = ["derive"]}
[dependencies.sqlx]
version = "0.8"
default-features = false
features = [
"runtime-tokio-rustls",
"macros",
"postgres",
"uuid",
"chrono",
"migrate"
]
